export interface IChildrenContext {
    children : JSX.Element | JSX.Element[]
}// Generated by https://quicktype.io

export interface IDrinks {
    drinks: Drink[];
}

export interface Drink {
    strCategory: string;
}
